config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  resources :rooms, except: [:new, :edit, :update]
  resources :messages
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :room, dependent: :destroy
    belongs_to :user
    validates :content, presence: true, length: {minimum: 2, maximum: 1000}

    after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :secrets
  def index; end

  def secrets; end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    redirect_to Room.first if Room.count > 0 
  end

  def show
    if !@room = Room.includes(:messages).find_by_id(params[:id]) || 
      flash[:alert] = 'Такой комнаты нет :('
      redirect_to action: :index
    end
    @messages = @room.messages.last(30);
    @rooms = Room.all
  end

  def create
    room = Room.new(room_params)
    room.user = current_user
    if !room.save
      flash[:alert] = 'Не создали :('
      redirect_to action: :index
    else
      redirect_to room
    end
  end

  def destroy
    @room = current_user.rooms.find_by_id(params[:id]) 
    if @room.nil? || !@room.delete
      flash[:alert] = 'Не удалили :('
    end
    redirect_to action: :index
  end

  private
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/_shared/_flashes.haml
- flash.each do |key, message|
  - if key == :alert then class = 'alert-danger' end
  - if key == :notice then class = 'alert-primary' end
  %p{class: "alert #{class}"}= message

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sandbox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .navbar.navbar-expand-md.navbar-dark.bg-primary
      .container
        = link_to 'Sandbox!', root_path, 'class' => 'navbar-brand'
        %button.navbar-toggler{'href' => '#', 'data-toggle' => 'collapse', 'data-target' => '#navbarTopMenu'}
        #navbarTopMenu.collapse.navbar-collapse
          %ul.navbar-nav
            %li.nav-item= link_to('Комнаты', rooms_path, {class: 'nav-link'})
            - if user_signed_in?
              %li.nav-item= link_to(I18n.t('users.links.sign_out'), destroy_user_session_path, {method: :delete, class: 'nav-link'})
            - else
              %li.nav-item= link_to(I18n.t('users.links.sign_up'), new_user_registration_path, {class: 'nav-link'})
              %li.nav-item= link_to(I18n.t('users.links.sign_in'), new_user_session_path, {class: 'nav-link'})
    .container
      - if notice
        %br/
        .alert.alert-primary{role: 'alert'}= notice
      - if alert
        %br/
        .alert.alert-danger{role: 'alert'}= alert
      %br/
      = yield

app/views/messages/_message.haml
%p.chat-message
  %span.text-muted.created_at="[#{message.created_at.strftime('%H:%M:%S')}]"
  %span.user="<#{message.user.email.split('@')[0]}>:" || "-Удален-"
  %span.content= message.content

app/views/pages/index.haml
%h1 Привет. Как дела?

app/views/pages/secrets.haml
%h1 Ты - приемный

app/views/rooms/_form.haml
= form_for room do |f|
  .form-row
    .col-9
      = f.text_field :name, class: 'form-control'
    .col
      = f.submit '+', class: 'btn btn-primary'

app/views/rooms/_list.haml
- if !rooms.nil? && !rooms.empty?
  .list-group
  - rooms.each do |room|
    = link_to room.name, room, class: "list-group-item list-group-item-action#{if room.id == current_room_id then " active" end}"
- else
  %p.alert.alert-info Не создано ни одной комнаты

app/views/rooms/index.haml
.row
  .col-3
    %h2 Комнаты
    - if user_signed_in?
      = render partial: "form", locals: {room: Room.new}
      %hr/
    .alert.alert-primary Комнат нет
  .col-9
    %h2#current_room_name Комнат нет.

app/views/rooms/show.haml
.row
  .col-3
    %h2 Комнаты
    - if user_signed_in?
      = render partial: "form", locals: {room: Room.new}
      %hr/
    = render partial: "list", locals: {rooms: @rooms, current_room_id: @room.id}
  .col-9
    %h2= @room.name
    - if @room.user == current_user
      = link_to 'Удалить', @room, {method: :delete, class: 'btn btn-danger'} 
    %hr/
    #chatbox{'data-room-id' => "#{@room.id}"}= render @room.messages
    %hr/
    = form_for Message.new, url: '#' do |f|
      .form-row
        .col-9= f.text_field :content, class: 'form-control'
        .col= f.submit 'Отпр.', class: 'btn btn-primary'